export const START_GAME = Symbol('START_GAME')
export const END_GAME = Symbol('END_GAME')
export const RESET_GAME = Symbol('RESET_GAME')
export const UPDATE_PLAYER_LOCATION = Symbol('UPDATE_PLAYER_LOCATION')
export const UPDATE_GAME_TIME = Symbol('UPDATE_GAME_TIME')
